version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-monitor
    restart: always
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-gemini}
      - SERVER_PORT=8080
    networks:
      - gemini-network

networks:
  gemini-network:
    driver: bridge
